import { useMemo, useRef, useState, type FormEvent } from 'react';
import { createDefaultScenario } from '../model/defaults';
import type { Issue, Office, ScenarioV2 } from '../model/contracts';
import { validateScenario } from '../model/validate';
import { canonicalStringify } from '../model/reproducibility';
import { useSimulationJob } from './useSimulationJob';
import { downloadJson } from './results/data';
import Results from './results/Results';
import '../styles/simulator.css';

function NumberField({label,name,value,onChange,min,max,step=1,unit,note}:{label:string;name:string;value:number;onChange:(value:number)=>void;min?:number;max?:number;step?:number;unit?:string;note?:string}) {
  const id=`scenario-${name.replace(/[^a-z0-9]/gi,'-')}`;
  return <label className="number-field" htmlFor={id}><span>{label}</span><span className="field-input"><input id={id} name={name} aria-label={label} type="number" value={Number.isFinite(value)?value:''} onChange={e=>onChange(e.target.value===''?NaN:Number(e.target.value))} min={Number.isFinite(min)?min:undefined} max={Number.isFinite(max)?max:undefined} step={step} aria-describedby={note?`${id}-note`:undefined}/>{unit&&<span>{unit}</span>}</span>{note&&<small id={`${id}-note`}>{note}</small>}</label>;
}
function explainIssue(issue:Issue) {
  if(issue.path.startsWith('offices')&&issue.path.endsWith('.floor'))return `Un ufficio è fuori dall’edificio. Correggi il piano nella lista oppure premi “Distribuisci gli uffici”. (${issue.path})`;
  if(issue.path.startsWith('offices')&&issue.path.endsWith('.lunchParticipation'))return `La partecipazione al pranzo deve essere una percentuale fra 0% e 100%. (${issue.path})`;
  return `${issue.message}${issue.path?` (${issue.path})`:''}`;
}
export default function Simulator() {
  const [draft,setDraft]=useState(createDefaultScenario),[officesPerFloor,setOfficesPerFloor]=useState(2),[employeesPerOffice,setEmployeesPerOffice]=useState(16),[formIssues,setFormIssues]=useState<readonly Issue[]>([]),[recordTrace,setRecordTrace]=useState(true);
  const form=useRef<HTMLFormElement>(null),job=useSimulationJob();
  const validation=useMemo(()=>validateScenario(draft),[draft]);
  const total=draft.offices.reduce((sum,o)=>sum+o.employees,0),busy=job.status==='running';
  const previous=job.result?busy||!validation.ok||canonicalStringify(job.result.scenario)!==canonicalStringify(draft):false;
  const physical=(key:keyof ScenarioV2['physical'],value:number)=>setDraft(s=>({...s,physical:{...s.physical,[key]:value}}));
  const traffic=(key:keyof ScenarioV2['traffic'],value:number)=>setDraft(s=>({...s,traffic:{...s.traffic,[key]:value}}));
  function updateOffice(index:number,key:keyof Office,value:string|number){setDraft(s=>({...s,offices:s.offices.map((o,i)=>i===index?{...o,[key]:value}:o)}));}
  function distribute() {
    if(!Number.isInteger(draft.upperFloors)||draft.upperFloors<1||draft.upperFloors>50||!Number.isInteger(officesPerFloor)||officesPerFloor<1||officesPerFloor>10||!Number.isSafeInteger(employeesPerOffice)||employeesPerOffice<1){setFormIssues([{code:'distribution',path:'',message:'Per distribuire gli uffici, inserisci 1–50 piani, 1–10 uffici per piano e almeno una persona per ufficio.'}]);return;}
    const offices:Office[]=Array.from({length:draft.upperFloors*officesPerFloor},(_,i)=>({id:`U${String(i+1).padStart(3,'0')}`,floor:Math.floor(i/officesPerFloor)+1,employees:employeesPerOffice,lunchStartHour:[12,13,14][i%3],lunchParticipation:.72}));
    setDraft(s=>({...s,offices,sourceOnlyMetadata:{...s.sourceOnlyMetadata,officePreset:'uniform-explicit',officePresetPeople:employeesPerOffice,officePresetPerFloor:officesPerFloor}}));setFormIssues([]);
  }
  function submit(event:FormEvent) {
    event.preventDefault();
    const check=validateScenario(draft);
    if(!check.ok){setFormIssues(check.issues);const target=form.current?.elements.namedItem(check.issues[0].path) as HTMLElement|null;if(target){let parent=target.parentElement;while(parent){if(parent instanceof HTMLDetailsElement)parent.open=true;parent=parent.parentElement;}target.focus();}return;}
    setFormIssues([]);job.start(check.scenario,['fifo','optimal','adaptive'],recordTrace?{policy:'adaptive',seed:check.scenario.seeds.simulation[0]}:null);
  }
  async function importScenario(file:File|undefined) {
    if(!file)return;
    if(file.size>2*1024*1024){setFormIssues([{code:'file',path:'',message:'Il file di configurazione supera 2 MB.'}]);return;}
    try {const value=JSON.parse(await file.text());const check=validateScenario(value.scenario??value);if(!check.ok){setFormIssues(check.issues);return;}setDraft(check.scenario);setFormIssues([]);}
    catch{setFormIssues([{code:'file',path:'',message:'Il file non contiene una configurazione JSON leggibile.'}]);}
  }
  return <div className="simulator"><form ref={form} onSubmit={submit} noValidate>
    <div className="config-heading"><p className="config-label">01 / Configura l’edificio</p><span className="mass-badge">80 kg per persona</span></div>
    <div className="building-inputs"><NumberField label="Piani sopra terra" name="upperFloors" value={draft.upperFloors} onChange={value=>setDraft(s=>({...s,upperFloors:value,traffic:{...s.traffic,internalTripsProbability:value===1?0:s.traffic.internalTripsProbability}}))} min={1} max={50} note="Il piano terra 0 è sempre presente e non si conta qui."/><NumberField label="Numero di ascensori" name="cabins" value={draft.cabins.length} onChange={value=>{if(!Number.isInteger(value)||value<1||value>8){setFormIssues([{code:'cars',path:'cabins',message:'Inserisci da 1 a 8 ascensori.'}]);return;}setDraft(s=>({...s,cabins:Array.from({length:value},(_,id)=>s.cabins[id]??{id,ratedLoadKg:1000,maxPeople:13})}));}} min={1} max={8} note="Ogni cabina conserva portata e posti individuali."/></div>
    <div className="people-config"><div><p className="config-label">02 / Distribuisci le persone</p><p className="config-intro">La lista attuale contiene <strong>{draft.offices.length} uffici</strong> e <strong>{Number.isFinite(total)?total:'—'} persone</strong>. Puoi mantenerla o creare una distribuzione uniforme.</p></div><div className="people-inputs"><NumberField label="Uffici per piano" name="officeGuide.count" value={officesPerFloor} onChange={setOfficesPerFloor} min={1} max={10}/><NumberField label="Persone per ufficio" name="officeGuide.people" value={employeesPerOffice} onChange={setEmployeesPerOffice} min={1}/><button type="button" className="quiet-button" onClick={distribute}>Distribuisci gli uffici</button></div><p className="field-note">L’azione crea un ufficio per ogni posizione dichiarata, con pausa alternata alle 12, 13 e 14 e partecipazione al pranzo del 72%. La lista completa è modificabile sotto. Cambiare i piani non sposta o cancella gli uffici.</p></div>
    <details className="advanced-config"><summary>Personalizza uffici e pause</summary><p>Ogni riga entra nei calcoli. Il totale si ricava dagli addetti di ciascun ufficio; la partecipazione al pranzo è una percentuale da 0% a 100%.</p><div className="table-scroll office-table" tabIndex={0} aria-label="Lista uffici, scorribile"><table><caption>Uffici effettivi dello scenario</caption><thead><tr><th>Ufficio</th><th>Piano</th><th>Persone</th><th>Pranzo (ora)</th><th>Partecipazione (%)</th><th>Azioni</th></tr></thead><tbody>{draft.offices.map((o,i)=><tr key={i}><th><label className="sr-only" htmlFor={`office-id-${i}`}>ID ufficio {i+1}</label><input id={`office-id-${i}`} name={`offices[${i}].id`} value={o.id} onChange={e=>updateOffice(i,'id',e.target.value)}/></th><td><NumberField label={`Piano ufficio ${i+1}`} name={`offices[${i}].floor`} value={o.floor} onChange={v=>updateOffice(i,'floor',v)} min={1} max={draft.upperFloors}/></td><td><NumberField label={`Persone ufficio ${i+1}`} name={`offices[${i}].employees`} value={o.employees} onChange={v=>updateOffice(i,'employees',v)} min={1}/></td><td><NumberField label={`Pranzo ufficio ${i+1}`} name={`offices[${i}].lunchStartHour`} value={o.lunchStartHour} onChange={v=>updateOffice(i,'lunchStartHour',v)} min={0} max={24} step={.25}/></td><td><NumberField label={`Partecipazione ufficio ${i+1}`} name={`offices[${i}].lunchParticipation`} value={Number((o.lunchParticipation*100).toFixed(10))} onChange={v=>updateOffice(i,'lunchParticipation',v/100)} min={0} max={100} step={.1} unit="%"/></td><td><button type="button" className="remove-office" aria-label={`Elimina ufficio ${o.id}`} disabled={draft.offices.length===1} onClick={()=>setDraft(s=>({...s,offices:s.offices.filter((_,idx)=>idx!==i)}))}>Rimuovi</button></td></tr>)}</tbody></table></div><button type="button" className="quiet-button" onClick={()=>setDraft(s=>({...s,offices:[...s.offices,{id:`U-NUOVO-${Date.now()}`,floor:1,employees:16,lunchStartHour:13,lunchParticipation:.72}]}))}>Aggiungi un ufficio</button></details>
    <details className="advanced-config"><summary>Capacità degli ascensori</summary><p>La portata limita i kg; il numero di posti limita le persone. La pianificazione mantiene il 4% di margine sul peso.</p><div className="capacity-list">{draft.cabins.map((c,i)=><fieldset key={c.id}><legend>Cabina {String.fromCharCode(65+c.id)}</legend><NumberField label="Portata" name={`cabins[${i}].ratedLoadKg`} value={c.ratedLoadKg} onChange={v=>setDraft(s=>({...s,cabins:s.cabins.map((car,j)=>j===i?{...car,ratedLoadKg:v}:car)}))} min={1} unit="kg"/><NumberField label="Limite di posti" name={`cabins[${i}].maxPeople`} value={c.maxPeople} onChange={v=>setDraft(s=>({...s,cabins:s.cabins.map((car,j)=>j===i?{...car,maxPeople:v}:car)}))} min={1} unit="persone"/><p className="field-note">Fisicamente: {Math.min(c.maxPeople,Math.floor(c.ratedLoadKg/80))} persone. Pianificabili: {Math.min(c.maxPeople,Math.floor(.96*c.ratedLoadKg/80))}. {c.ratedLoadKg<80?'La portata non consente una persona.':.96*c.ratedLoadKg<80?'Il margine impedisce il servizio pianificato.':''}</p></fieldset>)}</div><button type="button" className="quiet-button" onClick={()=>setDraft(s=>({...s,cabins:s.cabins.map(c=>({...c,ratedLoadKg:s.cabins[0].ratedLoadKg,maxPeople:s.cabins[0].maxPeople}))}))}>Applica i valori della cabina A a tutte</button></details>
    <details className="advanced-config"><summary>Orari e caratteristiche dell’edificio</summary><div className="advanced-grid"><NumberField label="Ingresso medio" name="traffic.arrivalMeanHour" value={draft.traffic.arrivalMeanHour} onChange={v=>traffic('arrivalMeanHour',v)} min={0} max={24} step={.01} unit="h"/><NumberField label="Variazione ingresso" name="traffic.arrivalSdMinutes" value={draft.traffic.arrivalSdMinutes} onChange={v=>traffic('arrivalSdMinutes',v)} min={0} unit="min"/><NumberField label="Uscita media" name="traffic.departureMeanHour" value={draft.traffic.departureMeanHour} onChange={v=>traffic('departureMeanHour',v)} min={0} max={24} step={.01} unit="h"/><NumberField label="Variazione uscita" name="traffic.departureSdMinutes" value={draft.traffic.departureSdMinutes} onChange={v=>traffic('departureSdMinutes',v)} min={0} unit="min"/><NumberField label="Durata pranzo" name="traffic.lunchDurationMinutes" value={draft.traffic.lunchDurationMinutes} onChange={v=>traffic('lunchDurationMinutes',v)} min={0} unit="min"/><NumberField label="Variazione inizio pranzo" name="traffic.lunchSdMinutes" value={draft.traffic.lunchSdMinutes} onChange={v=>traffic('lunchSdMinutes',v)} min={0} unit="min"/><NumberField label="Quota viaggi interni" name="traffic.internalTripsProbability" value={draft.traffic.internalTripsProbability} onChange={v=>traffic('internalTripsProbability',v)} min={0} max={1} step={.01} note={draft.upperFloors===1?'Con un solo piano sopra terra deve essere 0.':'Probabilità per addetto. Orario sorgente fisso 09–18.'}/><NumberField label="Altezza interpiano" name="physical.floorHeightM" value={draft.physical.floorHeightM} onChange={v=>physical('floorHeightM',v)} min={.01} step={.1} unit="m"/><NumberField label="Velocità" name="physical.speedMps" value={draft.physical.speedMps} onChange={v=>physical('speedMps',v)} min={.01} step={.1} unit="m/s"/><NumberField label="Accelerazione" name="physical.accelerationMps2" value={draft.physical.accelerationMps2} onChange={v=>physical('accelerationMps2',v)} min={.01} step={.1} unit="m/s²"/><NumberField label="Tempo porta" name="physical.doorBaseS" value={draft.physical.doorBaseS} onChange={v=>physical('doorBaseS',v)} min={0} step={.1} unit="s"/><NumberField label="Trasferimento per persona" name="physical.passengerTransferS" value={draft.physical.passengerTransferS} onChange={v=>physical('passengerTransferS',v)} min={0} step={.1} unit="s"/></div><p className="field-note">Ore in formato decimale: 7,5 significa 07:30. Le fasce fisse del parking sorgente restano dichiarate; cambiare gli orari non riscrive automaticamente queste regole.</p></details>
    <details className="advanced-config"><summary>Confronto e riproducibilità</summary><div className="advanced-grid"><NumberField label="Numero di repliche" name="seeds.simulation.length" value={draft.seeds.simulation.length} onChange={v=>{if(!/^\d+$/.test(draft.seeds.simulation[0]??'')){setFormIssues([{code:'seed',path:'seeds.simulation[0]',message:'Inserisci un primo seed intero prima di cambiare le repliche.'}]);return;}if(Number.isInteger(v)&&v>=1&&v<=8)setDraft(s=>({...s,seeds:{...s.seeds,simulation:Array.from({length:v},(_,i)=>String(BigInt(s.seeds.simulation[0]||'101')+BigInt(i*101)))}}));}} min={1} max={8} note="Una replica mostra un caso; almeno due permettono un confronto statistico appaiato."/><label className="number-field">Primo seed<input aria-label="Primo seed" name="seeds.simulation[0]" inputMode="numeric" value={draft.seeds.simulation[0]} onChange={e=>{const value=e.target.value;setDraft(s=>({...s,seeds:{...s.seeds,simulation:s.seeds.simulation.map((old,i)=>i===0?value:old)}}));}}/><small>Numero intero decimale. Lo stesso corpus è riusato dalle tre politiche.</small></label><NumberField label="Inizio orizzonte" name="startS" value={draft.startS/3600} onChange={v=>setDraft(s=>({...s,startS:v*3600}))} min={0} max={24} step={.25} unit="h"/><NumberField label="Fine orizzonte" name="endS" value={draft.endS/3600} onChange={v=>setDraft(s=>({...s,endS:v*3600}))} min={0} max={24} step={.25} unit="h"/></div><label className="checkbox-field"><input type="checkbox" checked={recordTrace} onChange={e=>setRecordTrace(e.target.checked)}/> Registra gli eventi della prima replica adattiva per consultarli passo dopo passo</label><p className="field-note">Ogni run conserva versione, seed, hash e dataset. Il calcolo termina all’orizzonte senza svuotare le code. I limiti di memoria producono un messaggio esplicito, mai un campione ridotto nascosto.</p><div className="configuration-tools"><button type="button" className="quiet-button" onClick={()=>downloadJson(draft,'ascensori-configurazione.json')}>Salva configurazione</button><label className="import-label">Apri configurazione JSON<input type="file" accept=".json,application/json" onChange={e=>void importScenario(e.target.files?.[0])}/></label><button type="button" className="quiet-button" onClick={()=>{setDraft(createDefaultScenario());setFormIssues([]);}}>Ripristina il riferimento</button></div></details>
    {formIssues.length>0&&<div className="form-errors" role="alert"><h3>Correggi la configurazione</h3><ul>{formIssues.slice(0,10).map((issue,i)=><li key={i}>{explainIssue(issue)}</li>)}</ul>{formIssues.length>10&&<p>Altri {formIssues.length-10} campi richiedono una correzione.</p>}</div>}
    <div className="scenario-summary"><span>{draft.cabins.length} cabine</span><span>{Number.isFinite(draft.upperFloors)?draft.upperFloors:'—'} piani + terra</span><span>{draft.offices.length} uffici</span><span>{Number.isFinite(total)?total:'—'} persone</span></div>
    <div className="run-actions"><button className="button" type="submit" disabled={busy}>{busy?'Confronto in corso…':'Esegui il confronto'} <span aria-hidden="true">↗︎</span></button>{busy&&<button type="button" className="quiet-button" onClick={job.cancel}>Annulla il calcolo</button>}<p>Tre politiche. Stesse richieste. Modifica e riesegui senza ricaricare.</p></div>
    <div className="run-status" role="status" aria-live="polite">{busy?(job.progress?.phase==='simulation'?`Simulazioni completate: ${job.progress.completedRuns??0} di ${job.progress.totalRuns??'…'}.`:'Preparazione del corpus e delle stime degli uffici…'):job.status==='done'?'Confronto completato. I risultati sono disponibili qui sotto.':job.status==='cancelled'?'Calcolo annullato. Puoi modificare la configurazione e rieseguire.':job.status==='error'?'Il calcolo non è stato completato.':!job.result?'Configura lo scenario, poi esegui per leggere le misure.':''}</div>
    {job.status==='error'&&<div className="form-errors" role="alert"><h3>Il caso richiede una correzione</h3><ul>{job.issues.map((issue,i)=><li key={i}>{explainIssue(issue)}</li>)}</ul></div>}
    {!validation.ok&&formIssues.length===0&&<p className="draft-warning">La bozza contiene campi da verificare: l’esecuzione ti mostrerà quali correggere.</p>}
  </form>{job.result&&<Results key={job.result.datasets.map(d=>d.datasetHash).join(':')} experiment={job.result} previous={previous}/>}</div>;
}
