import { useEffect } from 'react';
import AutomationExample from '../features/AutomationExample';
import RouteLink from '../components/RouteLink';
import { withBasePath } from '../navigation/paths';

const steps = [
  { n:'01', title:'Riceve una richiesta.', text:'Una persona indica il piano da cui parte e quello che vuole raggiungere. Il sistema conosce quindi la destinazione prima di scegliere la cabina.', technical:'Il modello usa l’ipotesi DCS: origine e destinazione sono note alla chiamata. Ogni richiesta registra tempo, percorso e massa fissa di 80 kg e corrisponde a un passeggero.', href:'domanda' },
  { n:'02', title:'Confronta le fermate possibili.', text:'Il sistema controlla dove si trovano le cabine, chi sta già viaggiando e quali fermate sono previste. Prova ad aggiungere la salita e la destinazione della nuova persona, rispettando posti e peso massimo.', technical:'Ogni piano candidato deve rispettare portata e numero di persone lungo l’intera sequenza. La pianificazione usa il margine conservativo 0,96. Un segmento già in movimento mantiene la destinazione.', href:'vincoli' },
  { n:'03', title:'Sceglie la cabina e le fermate.', text:'“Solo su chiamata” considera l’arrivo della cabina, il viaggio e i ritardi agli altri. “Chiamate e orari” e “Chiamate e previsione” confrontano anche l’attesa e il viaggio complessivi delle persone coinvolte. Se nessuna cabina può servire la chiamata rispettando i limiti, la persona resta in attesa.', technical:'Nei due ultimi sistemi il criterio si chiama J. Il nuovo percorso aggiunge la salita e la discesa dove l’aumento di J è minore: è una scelta locale, detta “greedy”, non la soluzione migliore garantita per tutta la giornata. “Optimal” è soltanto il nome interno del secondo sistema.', href:'politiche' },
  { n:'04', title:'Segue il servizio.', text:'La simulazione registra partenze, arrivi, persone che salgono e scendono. Puoi sapere chi aspetta, chi è in cabina e chi è arrivato. Quando una cabina termina una fermata, il sistema verifica anche le chiamate ancora da servire.', technical:'Le persone scendono prima che altre salgano; gli eventi condividono un ordine deterministico. La fine dell’attesa e la fine del viaggio sono registrate all’arrivo della cabina al piano di salita e di destinazione.', href:'metriche' },
  { n:'05', title:'Si prepara alla domanda futura.', text:'Con “Solo su chiamata”, la cabina libera resta all’ultima fermata. Con “Chiamate e orari”, si prepara nei piani previsti dalle fasce orarie. Con “Chiamate e previsione”, le abitudini simulate degli uffici aiutano a prepararsi alle uscite e ai ritorni dal pranzo, lasciando una cabina disponibile di riserva.', technical:'Le abitudini degli uffici sono stimate prima del confronto. Il riposizionamento usa soltanto cabine vuote, senza fermate assegnate, inattive da almeno 35 secondi e con posti pianificabili. I vincoli limitano i piani assegnabili nella decisione corrente.', href:'parking' },
];

export default function HowItWorks({ onReady }: { onReady: () => void }) {
  useEffect(()=>onReady(), [onReady]);
  return <article className="how-page container">
    <div className="breadcrumb"><RouteLink href="/">Home</RouteLink><span aria-hidden="true">/</span><span>Come funziona</span></div>
    <header className="how-intro"><p className="eyebrow"><span className="tiny-square"/>Dalla chiamata all'arrivo</p><h1>Una chiamata.<br/><em>Molte possibilità.</em></h1><div className="how-intro-bottom"><p>Automatizzare significa decidere quale cabina mandare, quali fermate fare e dove aspettare la prossima chiamata. Qui puoi capire il processo senza partire dalle formule, poi osservare le decisioni in un esempio calcolato.</p><RouteLink className="button" href="/come-funziona#esempio">Esplora un caso <span aria-hidden="true">↓</span></RouteLink></div></header>
    <nav className="how-outline" aria-label="Sommario di Come funziona"><a href="#processo">Il processo</a><a href="#esempio">Un esempio calcolato</a><a href="#leggere-grafici">Come leggere i grafici</a><a href="#approfondisci">Il modello tecnico</a></nav>
    <section id="processo" className="section how-process" aria-labelledby="process-title"><p className="eyebrow">01 / Il processo</p><div className="section-heading"><h2 id="process-title">Che cosa fa,<br/><em>concretamente.</em></h2><p>Una chiamata avvia la scelta. Posti e peso massimo limitano le possibilità. Il sistema confronta le fermate che gli ascensori possono fare.</p></div><figure className="process-schematic"><div><span>Chiamata</span><strong>Origine + destinazione</strong></div><span className="schematic-arrow" aria-hidden="true">→</span><div><span>Limiti</span><strong>Carichi + posti + tempi</strong></div><span className="schematic-arrow" aria-hidden="true">→</span><div><span>Scelta</span><strong>Cabina e fermate</strong></div><figcaption>Schema illustrativo del processo; i risultati numerici sono calcolati nell'esempio seguente.</figcaption></figure><div className="automation-steps">{steps.map(step=><article key={step.n}><span className="step-index">{step.n}</span><div><h3>{step.title}</h3><p>{step.text}</p><details><summary>Un passo più tecnico</summary><p>{step.technical}</p><RouteLink className="text-link" href={`/gli-algoritmi#${step.href}`}>Leggi il dettaglio del modello <span aria-hidden="true">↗︎</span></RouteLink></details></div></article>)}</div></section>
    <section id="esempio" className="section example-section" aria-labelledby="example-title"><p className="eyebrow">02 / Un caso controllato</p><div className="section-heading"><h2 id="example-title">Leggere una decisione,<br/><em>passo dopo passo.</em></h2><p>Questo esempio usa il motore della simulazione su un piccolo caso controllato. Le richieste e lo scenario sono espliciti: le assegnazioni, gli eventi e le misure arrivano dal calcolo.</p></div><div className="example-guide"><span aria-hidden="true">↳</span><p>Segui una persona dalla chiamata alla salita e all’arrivo. Guarda quale cabina viene scelta, quanto si aspetta e quante persone possono salire. La cabina più vicina può essere già piena o dover fare fermate che ritarderebbero gli altri.</p></div><AutomationExample/></section>
    <section id="leggere-grafici" className="section graph-reading" aria-labelledby="read-title"><p className="eyebrow">03 / Interpretare le misure</p><h2 id="read-title">I grafici hanno<br/><em>una storia precisa.</em></h2><div className="reading-grid"><article><span>Tempi per richiesta</span><h3>Prima l'attesa.<br/>Poi il viaggio.</h3><p>Le barre separano l’attesa prima di salire dal viaggio in cabina. I tempi sono in secondi e si possono confrontare con gli eventi registrati. Quando una persona non è ancora arrivata, il tempo completo del suo viaggio non è disponibile.</p></article><article><span>Carichi per cabina</span><h3>Due limiti.<br/>Una verifica continua.</h3><p>Il carico aumenta quando le persone salgono e diminuisce quando scendono. Il sistema verifica il peso massimo della cabina e, per scegliere le fermate, usa un margine prudente. Controlla sempre anche il numero di posti.</p></article><article><span>Decisioni ed eventi</span><h3>Il motivo,<br/>oltre il risultato.</h3><p>La registrazione mostra quando arriva una chiamata, quale cabina viene scelta e dove si ferma. Le tabelle riportano gli stessi dati dei grafici, così puoi leggere i valori anche senza seguire colori e linee.</p></article></div><p className="reading-note">Il piccolo esempio spiega come vengono prese le decisioni. Per confrontare i tre modi di organizzare gli ascensori, configura un edificio: le chiamate saranno uguali per tutti e vedrai anche chi sta ancora aspettando o viaggiando al termine.</p><RouteLink className="text-link" href="/#simulatore">Configura il tuo confronto <span aria-hidden="true">→</span></RouteLink></section>
    <section id="approfondisci" className="section technical-bridge" aria-labelledby="technical-title"><p className="eyebrow">04 / Scegli la profondità</p><h2 id="technical-title">Ora, se vuoi,<br/><em>entra nelle formule.</em></h2><p>La pagina Gli algoritmi spiega unità di misura, limiti, criterio J e come la previsione guida il riposizionamento delle cabine. Il PDF conserva il modello originale: V2 applica le correzioni approvate e la massa fissa di 80 kg, senza ereditare i risultati storici.</p><div className="hero-actions"><RouteLink className="button" href="/gli-algoritmi">Leggi gli algoritmi <span aria-hidden="true">↗︎</span></RouteLink><a className="text-link" href={withBasePath('/model/rapporto_ascensori.pdf')} target="_blank" rel="noreferrer">Apri il PDF matematico <span aria-hidden="true">↗︎</span><span className="sr-only"> (nuova scheda)</span></a></div><p className="reading-note">Questo strumento studia situazioni simulate: non comanda ascensori reali e non certifica un impianto.</p></section>
  </article>;
}
