import { useEffect } from 'react';
import AutomationExample from '../features/AutomationExample';
import RouteLink from '../components/RouteLink';

const steps = [
  { n:'01', title:'Riceve una richiesta.', text:'Una persona indica da dove parte e dove vuole andare. Origine e destinazione sono note alla chiamata: è l’ipotesi DCS del modello.', technical:'Ogni chiamata crea una richiesta con tempo, origine, destinazione e massa fissa di 80 kg. Una richiesta corrisponde a un passeggero.', href:'domanda' },
  { n:'02', title:'Valuta i piani possibili.', text:'Il sistema considera le cabine e dove inserire la nuova fermata di pickup e quella di destinazione. Controlla carichi, posti disponibili e tempi previsti.', technical:'Ogni piano candidato deve rispettare portata e numero di persone lungo l’intera sequenza. La pianificazione usa il margine conservativo 0,96. Un segmento già in movimento mantiene la destinazione.', href:'vincoli' },
  { n:'03', title:'Assegna una scelta fattibile.', text:'La politica confronta i candidati. La baseline usa un criterio euristico; greedy e adattiva valutano l’incremento del costo di attesa e viaggio. Se manca un piano fattibile, la richiesta aspetta.', technical:'La scelta è locale alla chiamata corrente. “Optimal” è un nome sorgente: non significa soluzione globalmente ottima della giornata.', href:'politiche' },
  { n:'04', title:'Segue il servizio.', text:'Il motore registra arrivi, sbarchi, imbarchi e porte. Una richiesta passa da attesa a bordo, poi a completata. Le richieste pendenti vengono rivalutate quando cambia lo stato.', technical:'Gli sbarchi precedono gli imbarchi; gli eventi condividono un ordine deterministico. L’attesa finisce al pickup e il viaggio alla destinazione, registrati all’arrivo della cabina.', href:'metriche' },
  { n:'05', title:'Si prepara alla domanda futura.', text:'Quando non c’è servizio pendente, l’adattiva può preposizionare cabine realmente libere, se la copertura attesa giustifica lo spostamento. Una cabina eleggibile resta di riserva.', technical:'Le abitudini degli uffici sono apprese offline. Il parking usa soltanto cabine vuote, senza piano, inattive da almeno 35 secondi e con posti pianificabili. I vincoli limitano i target nella decisione corrente.', href:'parking' },
];

export default function HowItWorks({ onReady }: { onReady: () => void }) {
  useEffect(()=>onReady(), [onReady]);
  return <article className="how-page container">
    <div className="breadcrumb"><RouteLink href="/">Home</RouteLink><span aria-hidden="true">/</span><span>Come funziona</span></div>
    <header className="how-intro"><p className="eyebrow"><span className="tiny-square"/>Dalla chiamata all'arrivo</p><h1>Una chiamata.<br/><em>Molte possibilità.</em></h1><div className="how-intro-bottom"><p>Automatizzare significa valutare che cosa può fare ogni cabina, scegliere un piano fattibile e seguirlo nel tempo. Qui puoi leggere il processo senza partire dalle formule, poi osservare le decisioni in un caso calcolato.</p><RouteLink className="button" href="/come-funziona#esempio">Esplora un caso <span aria-hidden="true">↓</span></RouteLink></div></header>
    <nav className="how-outline" aria-label="Sommario di Come funziona"><a href="#processo">Il processo</a><a href="#esempio">Un esempio calcolato</a><a href="#leggere-grafici">Come leggere i grafici</a><a href="#approfondisci">Il modello tecnico</a></nav>
    <section id="processo" className="section how-process" aria-labelledby="process-title"><p className="eyebrow">01 / Il processo</p><div className="section-heading"><h2 id="process-title">Che cosa fa,<br/><em>concretamente.</em></h2><p>La domanda fornisce le chiamate. Le capacità delimitano le possibilità. La politica sceglie tra le possibilità rimaste.</p></div><figure className="process-schematic"><div><span>Input</span><strong>Origine + destinazione</strong></div><span className="schematic-arrow" aria-hidden="true">→</span><div><span>Vincoli</span><strong>Carichi + posti + tempi</strong></div><span className="schematic-arrow" aria-hidden="true">→</span><div><span>Scelta</span><strong>Un piano fattibile</strong></div><figcaption>Schema illustrativo del processo; i risultati numerici sono calcolati nell'esempio seguente.</figcaption></figure><div className="automation-steps">{steps.map(step=><article key={step.n}><span className="step-index">{step.n}</span><div><h3>{step.title}</h3><p>{step.text}</p><details><summary>Un passo più tecnico</summary><p>{step.technical}</p><RouteLink className="text-link" href={`/gli-algoritmi#${step.href}`}>Leggi il dettaglio del modello <span aria-hidden="true">↗︎</span></RouteLink></details></div></article>)}</div></section>
    <section id="esempio" className="section example-section" aria-labelledby="example-title"><p className="eyebrow">02 / Un caso controllato</p><div className="section-heading"><h2 id="example-title">Leggere una decisione,<br/><em>passo dopo passo.</em></h2><p>Questo esempio usa il motore della simulazione su un piccolo caso controllato. Le richieste e lo scenario sono espliciti: le assegnazioni, gli eventi e le misure arrivano dal calcolo.</p></div><div className="example-guide"><span aria-hidden="true">↳</span><p>Segui una richiesta dalla chiamata al pickup e alla destinazione. Confronta il piano scelto, l'attesa e il carico delle cabine. Un candidato vicino può essere escluso dai vincoli, oppure introdurre più ritardo agli altri.</p></div><AutomationExample/></section>
    <section id="leggere-grafici" className="section graph-reading" aria-labelledby="read-title"><p className="eyebrow">03 / Interpretare le misure</p><h2 id="read-title">I grafici hanno<br/><em>una storia precisa.</em></h2><div className="reading-grid"><article><span>Tempi per richiesta</span><h3>Prima l'attesa.<br/>Poi il viaggio.</h3><p>La timeline distingue il tempo fra chiamata e pickup dal tempo fra pickup e destinazione. Le unità e i timestamp permettono di collegare il grafico agli eventi. Una richiesta incompleta non ha un viaggio completato da misurare.</p></article><article><span>Carichi per cabina</span><h3>Due limiti.<br/>Una verifica continua.</h3><p>Il carico cambia con sbarchi e imbarchi effettivi. Il limite fisico e quello conservativo di pianificazione sono distinti: il secondo protegge la scelta dei piani, il primo vincola l'imbarco.</p></article><article><span>Decisioni e trace</span><h3>Il motivo,<br/>oltre il risultato.</h3><p>Il dettaglio degli eventi collega chiamate, assegnazioni e fermate. Le tabelle accessibili riportano le stesse misure dei grafici, così puoi leggere i dati senza dipendere dal colore o dalla rappresentazione.</p></article></div><p className="reading-note">Il caso piccolo spiega il funzionamento. Per confrontare il servizio su una giornata, configura uno scenario completo: stesso dataset per tutte le politiche, orizzonte finito e richieste non completate visibili.</p><RouteLink className="text-link" href="/#simulatore">Configura il tuo confronto <span aria-hidden="true">→</span></RouteLink></section>
    <section id="approfondisci" className="section technical-bridge" aria-labelledby="technical-title"><p className="eyebrow">04 / Scegli la profondità</p><h2 id="technical-title">Ora, se vuoi,<br/><em>entra nelle formule.</em></h2><p>La pagina Gli algoritmi esplicita unità, vincoli, costo J, previsione e parking. Il PDF conserva il modello originale: V2 applica le correzioni approvate e la massa fissa di 80 kg, senza ereditare i risultati storici.</p><div className="hero-actions"><RouteLink className="button" href="/gli-algoritmi">Leggi gli algoritmi <span aria-hidden="true">↗︎</span></RouteLink><a className="text-link" href="/model/rapporto_ascensori.pdf" target="_blank" rel="noreferrer">Apri il PDF matematico <span aria-hidden="true">↗︎</span><span className="sr-only"> (nuova scheda)</span></a></div><p className="reading-note">Uno strumento di studio su scenari sintetici. Non è un controllo hardware né una certificazione di un impianto.</p></section>
  </article>;
}
